adam_epsilon: 1.0e-08
auto_scale_batch_size: null
benchmark: true
data_aug: []
data_dir: data
default_root_dir: .
deterministic: false
distributed_backend: dp
early_stop_callback: false
eval_batch_size: 2
generated_data_files: []
gpus: -1
gradient_accumulation_steps: 16
include_data_type: true
learning_rate: 0.0002
max_grad_norm: 1.0
max_output_length: 200
max_seq_length: 512
model_name_or_path: t5-base
n_gpu: 1
num_of_workers: 4
num_sample_rows: 3
num_train_epochs: 30
output_dir: .
resume_from_checkpoint: null
seed: 42
train_batch_size: 2
use_modified_network: true
warmup_steps: 0
weight_decay: 0.0
